FROM python:3.9-slim as colibry

ENV COLIBRY_LIBRARY_PATH="/app/library"

COPY requirements.txt /app/requirements.txt
COPY calibre-python /app/calibre-python

WORKDIR /app/
RUN apt-get update && \
    apt-get install curl -y && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y && \
    pip install -r requirements.txt && \
    apt-get remove curl -y && \
    rustup self uninstall && \
    apt-get autoremove && \
    apt-get clean

COPY dashboard /app/dashboard

WORKDIR /app/dashboard
EXPOSE 8050
CMD ["gunicorn", "-b", "0.0.0.0:8050", "--reload", "app:server"]
