name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    name: "Ruff"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install ruff==0.4.0
    - run: ruff format --check
    - run: ruff check .

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
